local map = {}

map.scene = {
	[2005]={map_id=2005,name=[[荆州]],logic_id=3,scene_count=1,mapType=0,x=536,y=6725,isPVP=0,canAvoidwar=0,lvLimit=0,well_minlv=32,well_maxlv=40,isMining=0,hangPoints={},noHang=0,sceneMove={},fog=0,isDoubleLayer=0,revive={1,0,60},reviveItem={{10031,1,1}},reviveNowHpPre=80,reviveGoHomeHpPre=20,loadList={},can_collect_revive=0,can_use_pet=1,can_fly=1,can_task_fly=1,can_normal_jump=1,normal_jump_ban={},show_enemy=0,mp3=5,die_txt=[[您可以通过锻铸，神兵，铁骑，神将，宝物等方式提升实力]],seeWidth=800,seeHeight=500}
}

map.mapconf = {
	[2005]={
		[1]={cd=0,cnt=0,callback=[[time]],condition_cmd1=[[]],condition_arg1={},condition_cmd2=[[]],condition_arg2={},condition_cmd3=[[]],condition_arg3={},condition_cmd4=[[]],condition_arg4={},condition_cmd5=[[]],condition_arg5={},action_cmd1=[[new_monster_group]],action_arg1={0},action_cmd2=[[]],action_arg2={},action_cmd3=[[]],action_arg3={},action_cmd4=[[]],action_arg4={},action_cmd5=[[]],action_arg5={}},
		[2]={cd=0,cnt=1,callback=[[time]],condition_cmd1=[[]],condition_arg1={},condition_cmd2=[[]],condition_arg2={},condition_cmd3=[[]],condition_arg3={},condition_cmd4=[[]],condition_arg4={},condition_cmd5=[[]],condition_arg5={},action_cmd1=[[new_collect_group]],action_arg1={1},action_cmd2=[[new_monster_group]],action_arg2={1},action_cmd3=[[]],action_arg3={},action_cmd4=[[]],action_arg4={},action_cmd5=[[]],action_arg5={}},
		[7]={cd=0,cnt=0,callback=[[time]],condition_cmd1=[[area_has_human]],condition_arg1={5},condition_cmd2=[[]],condition_arg2={},condition_cmd3=[[]],condition_arg3={},condition_cmd4=[[]],condition_arg4={},condition_cmd5=[[]],condition_arg5={},action_cmd1=[[jump]],action_arg1={5,2002,8308,5630},action_cmd2=[[]],action_arg2={},action_cmd3=[[]],action_arg3={},action_cmd4=[[]],action_arg4={},action_cmd5=[[]],action_arg5={}},
		[8]={cd=0,cnt=0,callback=[[time]],condition_cmd1=[[area_has_human]],condition_arg1={6},condition_cmd2=[[]],condition_arg2={},condition_cmd3=[[]],condition_arg3={},condition_cmd4=[[]],condition_arg4={},condition_cmd5=[[]],condition_arg5={},action_cmd1=[[jump]],action_arg1={6,2200,624,347},action_cmd2=[[]],action_arg2={},action_cmd3=[[]],action_arg3={},action_cmd4=[[]],action_arg4={},action_cmd5=[[]],action_arg5={}},
		[9]={cd=0,cnt=0,callback=[[time]],condition_cmd1=[[area_has_human]],condition_arg1={99},condition_cmd2=[[]],condition_arg2={},condition_cmd3=[[]],condition_arg3={},condition_cmd4=[[]],condition_arg4={},condition_cmd5=[[]],condition_arg5={},action_cmd1=[[jump]],action_arg1={99,3001,3063,2312},action_cmd2=[[]],action_arg2={},action_cmd3=[[]],action_arg3={},action_cmd4=[[]],action_arg4={},action_cmd5=[[]],action_arg5={}},
		[10]={cd=0,cnt=0,callback=[[time]],condition_cmd1=[[area_has_human]],condition_arg1={10},condition_cmd2=[[]],condition_arg2={},condition_cmd3=[[]],condition_arg3={},condition_cmd4=[[]],condition_arg4={},condition_cmd5=[[]],condition_arg5={},action_cmd1=[[jump]],action_arg1={10,2010,6081,6946},action_cmd2=[[]],action_arg2={},action_cmd3=[[]],action_arg3={},action_cmd4=[[]],action_arg4={},action_cmd5=[[]],action_arg5={}},
		[301]={cd=0,cnt=0,callback=[[ref]],condition_cmd1=[[]],condition_arg1={},condition_cmd2=[[]],condition_arg2={},condition_cmd3=[[]],condition_arg3={},condition_cmd4=[[]],condition_arg4={},condition_cmd5=[[]],condition_arg5={},action_cmd1=[[new_monster_group_fix]],action_arg1={11},action_cmd2=[[]],action_arg2={},action_cmd3=[[]],action_arg3={},action_cmd4=[[]],action_arg4={},action_cmd5=[[]],action_arg5={}},
		[302]={cd=0,cnt=0,callback=[[ref]],condition_cmd1=[[]],condition_arg1={},condition_cmd2=[[]],condition_arg2={},condition_cmd3=[[]],condition_arg3={},condition_cmd4=[[]],condition_arg4={},condition_cmd5=[[]],condition_arg5={},action_cmd1=[[new_monster_group_fix]],action_arg1={12},action_cmd2=[[]],action_arg2={},action_cmd3=[[]],action_arg3={},action_cmd4=[[]],action_arg4={},action_cmd5=[[]],action_arg5={}},
		[303]={cd=0,cnt=0,callback=[[ref]],condition_cmd1=[[]],condition_arg1={},condition_cmd2=[[]],condition_arg2={},condition_cmd3=[[]],condition_arg3={},condition_cmd4=[[]],condition_arg4={},condition_cmd5=[[]],condition_arg5={},action_cmd1=[[new_monster_group_fix]],action_arg1={13},action_cmd2=[[]],action_arg2={},action_cmd3=[[]],action_arg3={},action_cmd4=[[]],action_arg4={},action_cmd5=[[]],action_arg5={}},
		[340]={cd=0,cnt=1,callback=[[time]],condition_cmd1=[[not_area_has_monster_id]],condition_arg1={-1,3000001,1},condition_cmd2=[[]],condition_arg2={},condition_cmd3=[[]],condition_arg3={},condition_cmd4=[[]],condition_arg4={},condition_cmd5=[[]],condition_arg5={},action_cmd1=[[ref_map]],action_arg1={{301,302,303}},action_cmd2=[[]],action_arg2={},action_cmd3=[[]],action_arg3={},action_cmd4=[[]],action_arg4={},action_cmd5=[[]],action_arg5={}},
		[341]={cd=3605,cnt=0,callback=[[time]],condition_cmd1=[[finish_simple]],condition_arg1={340,3600},condition_cmd2=[[]],condition_arg2={},condition_cmd3=[[]],condition_arg3={},condition_cmd4=[[]],condition_arg4={},condition_cmd5=[[]],condition_arg5={},action_cmd1=[[ref_map]],action_arg1={351},action_cmd2=[[]],action_arg2={},action_cmd3=[[]],action_arg3={},action_cmd4=[[]],action_arg4={},action_cmd5=[[]],action_arg5={}},
		[351]={cd=0,cnt=0,callback=[[ref]],condition_cmd1=[[not_map_has_monster_group_id]],condition_arg1={11},condition_cmd2=[[not_map_has_monster_group_id]],condition_arg2={12},condition_cmd3=[[not_map_has_monster_group_id]],condition_arg3={13},condition_cmd4=[[]],condition_arg4={},condition_cmd5=[[]],condition_arg5={},action_cmd1=[[]],action_arg1={},action_cmd2=[[]],action_arg2={},action_cmd3=[[]],action_arg3={},action_cmd4=[[]],action_arg4={},action_cmd5=[[]],action_arg5={}},
		[361]={cd=60,cnt=0,callback=[[time]],condition_cmd1=[[finish_recur]],condition_arg1={351,50},condition_cmd2=[[]],condition_arg2={},condition_cmd3=[[]],condition_arg3={},condition_cmd4=[[]],condition_arg4={},condition_cmd5=[[]],condition_arg5={},action_cmd1=[[ref_map]],action_arg1={{301,302,303}},action_cmd2=[[]],action_arg2={},action_cmd3=[[]],action_arg3={},action_cmd4=[[]],action_arg4={},action_cmd5=[[]],action_arg5={}}
	}
}

return map